package com.cimc.senheyun.dao;

import com.cimc.senheyun.po.TaPerature;

public interface TaPeratureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_perature_equipmet_data_new
     *
     * @mbg.generated
     */
    int insert(TaPerature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_perature_equipmet_data_new
     *
     * @mbg.generated
     */
    int insertSelective(TaPerature record);
}