package com.cimc.senheyun.dao;

import com.cimc.senheyun.po.TaTfEquipmetData;

public interface TaTfEquipmetDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_tf_equipmet_data_new
     *
     * @mbg.generated
     */
    int insert(TaTfEquipmetData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_tf_equipmet_data_new
     *
     * @mbg.generated
     */
    int insertSelective(TaTfEquipmetData record);
}