package com.cimc.senheyun.dao;

import com.cimc.senheyun.po.VdToken;
import com.cimc.senheyun.po.VdTokenExample;
import org.apache.ibatis.annotations.Param;

public interface VdTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_token
     *
     * @mbg.generated
     */
    int insert(VdToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_token
     *
     * @mbg.generated
     */
    int insertSelective(VdToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_token
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VdToken record, @Param("example") VdTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_token
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VdToken record, @Param("example") VdTokenExample example);
}