package com.cimc.senheyun.po;

import java.math.BigDecimal;
import java.util.Date;

public class TaTfEquipmetData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.pk_equipment
     *
     * @mbg.generated
     */
    private String pkEquipment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.dataTime
     *
     * @mbg.generated
     */
    private Date datatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.deviceAlert
     *
     * @mbg.generated
     */
    private Integer devicealert;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.deviceOperatePattern
     *
     * @mbg.generated
     */
    private Integer deviceoperatepattern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.pushFatStatus
     *
     * @mbg.generated
     */
    private Integer pushfatstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.pushFatDoorStatus1
     *
     * @mbg.generated
     */
    private Integer pushfatdoorstatus1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.pushFatDoorStatus2
     *
     * @mbg.generated
     */
    private Integer pushfatdoorstatus2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.pushFatDoorStatus3
     *
     * @mbg.generated
     */
    private Integer pushfatdoorstatus3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.pushFatDoorStatus4
     *
     * @mbg.generated
     */
    private Integer pushfatdoorstatus4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.pushFatPumpStatus
     *
     * @mbg.generated
     */
    private Integer pushfatpumpstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.pushFatNumber
     *
     * @mbg.generated
     */
    private Integer pushfatnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPFatWeight
     *
     * @mbg.generated
     */
    private BigDecimal kpfatweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPSecondFatWeight
     *
     * @mbg.generated
     */
    private BigDecimal kpsecondfatweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.XSAFatWeight
     *
     * @mbg.generated
     */
    private BigDecimal xsafatweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPFatGross
     *
     * @mbg.generated
     */
    private BigDecimal kpfatgross;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPSecondFatGross
     *
     * @mbg.generated
     */
    private BigDecimal kpsecondfatgross;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.XSAFatGross
     *
     * @mbg.generated
     */
    private BigDecimal xsafatgross;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPFatLength
     *
     * @mbg.generated
     */
    private BigDecimal kpfatlength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPSecondFatLength
     *
     * @mbg.generated
     */
    private BigDecimal kpsecondfatlength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.XSAFatLength
     *
     * @mbg.generated
     */
    private BigDecimal xsafatlength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPFatTotalLength
     *
     * @mbg.generated
     */
    private BigDecimal kpfattotallength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPSecondFatTotalLength
     *
     * @mbg.generated
     */
    private BigDecimal kpsecondfattotallength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.XSAFatTotalLength
     *
     * @mbg.generated
     */
    private BigDecimal xsafattotallength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.instantFlow
     *
     * @mbg.generated
     */
    private BigDecimal instantflow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.pumpLaterPressure
     *
     * @mbg.generated
     */
    private BigDecimal pumplaterpressure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPFatTanklevel
     *
     * @mbg.generated
     */
    private BigDecimal kpfattanklevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPSecondFatTanklevel
     *
     * @mbg.generated
     */
    private BigDecimal kpsecondfattanklevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.XSAFatTanklevel
     *
     * @mbg.generated
     */
    private BigDecimal xsafattanklevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPFatWeightValue
     *
     * @mbg.generated
     */
    private BigDecimal kpfatweightvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPSecondFatWeightValue
     *
     * @mbg.generated
     */
    private BigDecimal kpsecondfatweightvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.XSAFatWeightValue
     *
     * @mbg.generated
     */
    private BigDecimal xsafatweightvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPFatCompensationValue
     *
     * @mbg.generated
     */
    private BigDecimal kpfatcompensationvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPSecondFatCompensationValue
     *
     * @mbg.generated
     */
    private BigDecimal kpsecondfatcompensationvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.XSAFatCompensationValue
     *
     * @mbg.generated
     */
    private BigDecimal xsafatcompensationvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.pumpLaterPressureLowValue
     *
     * @mbg.generated
     */
    private BigDecimal pumplaterpressurelowvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.FlowLowValue
     *
     * @mbg.generated
     */
    private BigDecimal flowlowvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.pumpFrequencyValue
     *
     * @mbg.generated
     */
    private BigDecimal pumpfrequencyvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPPushFatNumber
     *
     * @mbg.generated
     */
    private BigDecimal kppushfatnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.KPSecondPushFatNumber
     *
     * @mbg.generated
     */
    private BigDecimal kpsecondpushfatnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ta_tf_equipmet_data_new.XSAPushFatNumber
     *
     * @mbg.generated
     */
    private BigDecimal xsapushfatnumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_tf_equipmet_data_new
     *
     * @mbg.generated
     */
    public TaTfEquipmetData(String pkEquipment, Date datatime, Integer devicealert, Integer deviceoperatepattern, Integer pushfatstatus, Integer pushfatdoorstatus1, Integer pushfatdoorstatus2, Integer pushfatdoorstatus3, Integer pushfatdoorstatus4, Integer pushfatpumpstatus, Integer pushfatnumber, BigDecimal kpfatweight, BigDecimal kpsecondfatweight, BigDecimal xsafatweight, BigDecimal kpfatgross, BigDecimal kpsecondfatgross, BigDecimal xsafatgross, BigDecimal kpfatlength, BigDecimal kpsecondfatlength, BigDecimal xsafatlength, BigDecimal kpfattotallength, BigDecimal kpsecondfattotallength, BigDecimal xsafattotallength, BigDecimal instantflow, BigDecimal pumplaterpressure, BigDecimal kpfattanklevel, BigDecimal kpsecondfattanklevel, BigDecimal xsafattanklevel, BigDecimal kpfatweightvalue, BigDecimal kpsecondfatweightvalue, BigDecimal xsafatweightvalue, BigDecimal kpfatcompensationvalue, BigDecimal kpsecondfatcompensationvalue, BigDecimal xsafatcompensationvalue, BigDecimal pumplaterpressurelowvalue, BigDecimal flowlowvalue, BigDecimal pumpfrequencyvalue, BigDecimal kppushfatnumber, BigDecimal kpsecondpushfatnumber, BigDecimal xsapushfatnumber) {
        this.pkEquipment = pkEquipment;
        this.datatime = datatime;
        this.devicealert = devicealert;
        this.deviceoperatepattern = deviceoperatepattern;
        this.pushfatstatus = pushfatstatus;
        this.pushfatdoorstatus1 = pushfatdoorstatus1;
        this.pushfatdoorstatus2 = pushfatdoorstatus2;
        this.pushfatdoorstatus3 = pushfatdoorstatus3;
        this.pushfatdoorstatus4 = pushfatdoorstatus4;
        this.pushfatpumpstatus = pushfatpumpstatus;
        this.pushfatnumber = pushfatnumber;
        this.kpfatweight = kpfatweight;
        this.kpsecondfatweight = kpsecondfatweight;
        this.xsafatweight = xsafatweight;
        this.kpfatgross = kpfatgross;
        this.kpsecondfatgross = kpsecondfatgross;
        this.xsafatgross = xsafatgross;
        this.kpfatlength = kpfatlength;
        this.kpsecondfatlength = kpsecondfatlength;
        this.xsafatlength = xsafatlength;
        this.kpfattotallength = kpfattotallength;
        this.kpsecondfattotallength = kpsecondfattotallength;
        this.xsafattotallength = xsafattotallength;
        this.instantflow = instantflow;
        this.pumplaterpressure = pumplaterpressure;
        this.kpfattanklevel = kpfattanklevel;
        this.kpsecondfattanklevel = kpsecondfattanklevel;
        this.xsafattanklevel = xsafattanklevel;
        this.kpfatweightvalue = kpfatweightvalue;
        this.kpsecondfatweightvalue = kpsecondfatweightvalue;
        this.xsafatweightvalue = xsafatweightvalue;
        this.kpfatcompensationvalue = kpfatcompensationvalue;
        this.kpsecondfatcompensationvalue = kpsecondfatcompensationvalue;
        this.xsafatcompensationvalue = xsafatcompensationvalue;
        this.pumplaterpressurelowvalue = pumplaterpressurelowvalue;
        this.flowlowvalue = flowlowvalue;
        this.pumpfrequencyvalue = pumpfrequencyvalue;
        this.kppushfatnumber = kppushfatnumber;
        this.kpsecondpushfatnumber = kpsecondpushfatnumber;
        this.xsapushfatnumber = xsapushfatnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ta_tf_equipmet_data_new
     *
     * @mbg.generated
     */
    public TaTfEquipmetData() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.pk_equipment
     *
     * @return the value of ta_tf_equipmet_data_new.pk_equipment
     *
     * @mbg.generated
     */
    public String getPkEquipment() {
        return pkEquipment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.pk_equipment
     *
     * @param pkEquipment the value for ta_tf_equipmet_data_new.pk_equipment
     *
     * @mbg.generated
     */
    public void setPkEquipment(String pkEquipment) {
        this.pkEquipment = pkEquipment == null ? null : pkEquipment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.dataTime
     *
     * @return the value of ta_tf_equipmet_data_new.dataTime
     *
     * @mbg.generated
     */
    public Date getDatatime() {
        return datatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.dataTime
     *
     * @param datatime the value for ta_tf_equipmet_data_new.dataTime
     *
     * @mbg.generated
     */
    public void setDatatime(Date datatime) {
        this.datatime = datatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.deviceAlert
     *
     * @return the value of ta_tf_equipmet_data_new.deviceAlert
     *
     * @mbg.generated
     */
    public Integer getDevicealert() {
        return devicealert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.deviceAlert
     *
     * @param devicealert the value for ta_tf_equipmet_data_new.deviceAlert
     *
     * @mbg.generated
     */
    public void setDevicealert(Integer devicealert) {
        this.devicealert = devicealert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.deviceOperatePattern
     *
     * @return the value of ta_tf_equipmet_data_new.deviceOperatePattern
     *
     * @mbg.generated
     */
    public Integer getDeviceoperatepattern() {
        return deviceoperatepattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.deviceOperatePattern
     *
     * @param deviceoperatepattern the value for ta_tf_equipmet_data_new.deviceOperatePattern
     *
     * @mbg.generated
     */
    public void setDeviceoperatepattern(Integer deviceoperatepattern) {
        this.deviceoperatepattern = deviceoperatepattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.pushFatStatus
     *
     * @return the value of ta_tf_equipmet_data_new.pushFatStatus
     *
     * @mbg.generated
     */
    public Integer getPushfatstatus() {
        return pushfatstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.pushFatStatus
     *
     * @param pushfatstatus the value for ta_tf_equipmet_data_new.pushFatStatus
     *
     * @mbg.generated
     */
    public void setPushfatstatus(Integer pushfatstatus) {
        this.pushfatstatus = pushfatstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.pushFatDoorStatus1
     *
     * @return the value of ta_tf_equipmet_data_new.pushFatDoorStatus1
     *
     * @mbg.generated
     */
    public Integer getPushfatdoorstatus1() {
        return pushfatdoorstatus1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.pushFatDoorStatus1
     *
     * @param pushfatdoorstatus1 the value for ta_tf_equipmet_data_new.pushFatDoorStatus1
     *
     * @mbg.generated
     */
    public void setPushfatdoorstatus1(Integer pushfatdoorstatus1) {
        this.pushfatdoorstatus1 = pushfatdoorstatus1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.pushFatDoorStatus2
     *
     * @return the value of ta_tf_equipmet_data_new.pushFatDoorStatus2
     *
     * @mbg.generated
     */
    public Integer getPushfatdoorstatus2() {
        return pushfatdoorstatus2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.pushFatDoorStatus2
     *
     * @param pushfatdoorstatus2 the value for ta_tf_equipmet_data_new.pushFatDoorStatus2
     *
     * @mbg.generated
     */
    public void setPushfatdoorstatus2(Integer pushfatdoorstatus2) {
        this.pushfatdoorstatus2 = pushfatdoorstatus2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.pushFatDoorStatus3
     *
     * @return the value of ta_tf_equipmet_data_new.pushFatDoorStatus3
     *
     * @mbg.generated
     */
    public Integer getPushfatdoorstatus3() {
        return pushfatdoorstatus3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.pushFatDoorStatus3
     *
     * @param pushfatdoorstatus3 the value for ta_tf_equipmet_data_new.pushFatDoorStatus3
     *
     * @mbg.generated
     */
    public void setPushfatdoorstatus3(Integer pushfatdoorstatus3) {
        this.pushfatdoorstatus3 = pushfatdoorstatus3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.pushFatDoorStatus4
     *
     * @return the value of ta_tf_equipmet_data_new.pushFatDoorStatus4
     *
     * @mbg.generated
     */
    public Integer getPushfatdoorstatus4() {
        return pushfatdoorstatus4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.pushFatDoorStatus4
     *
     * @param pushfatdoorstatus4 the value for ta_tf_equipmet_data_new.pushFatDoorStatus4
     *
     * @mbg.generated
     */
    public void setPushfatdoorstatus4(Integer pushfatdoorstatus4) {
        this.pushfatdoorstatus4 = pushfatdoorstatus4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.pushFatPumpStatus
     *
     * @return the value of ta_tf_equipmet_data_new.pushFatPumpStatus
     *
     * @mbg.generated
     */
    public Integer getPushfatpumpstatus() {
        return pushfatpumpstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.pushFatPumpStatus
     *
     * @param pushfatpumpstatus the value for ta_tf_equipmet_data_new.pushFatPumpStatus
     *
     * @mbg.generated
     */
    public void setPushfatpumpstatus(Integer pushfatpumpstatus) {
        this.pushfatpumpstatus = pushfatpumpstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.pushFatNumber
     *
     * @return the value of ta_tf_equipmet_data_new.pushFatNumber
     *
     * @mbg.generated
     */
    public Integer getPushfatnumber() {
        return pushfatnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.pushFatNumber
     *
     * @param pushfatnumber the value for ta_tf_equipmet_data_new.pushFatNumber
     *
     * @mbg.generated
     */
    public void setPushfatnumber(Integer pushfatnumber) {
        this.pushfatnumber = pushfatnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPFatWeight
     *
     * @return the value of ta_tf_equipmet_data_new.KPFatWeight
     *
     * @mbg.generated
     */
    public BigDecimal getKpfatweight() {
        return kpfatweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPFatWeight
     *
     * @param kpfatweight the value for ta_tf_equipmet_data_new.KPFatWeight
     *
     * @mbg.generated
     */
    public void setKpfatweight(BigDecimal kpfatweight) {
        this.kpfatweight = kpfatweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPSecondFatWeight
     *
     * @return the value of ta_tf_equipmet_data_new.KPSecondFatWeight
     *
     * @mbg.generated
     */
    public BigDecimal getKpsecondfatweight() {
        return kpsecondfatweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPSecondFatWeight
     *
     * @param kpsecondfatweight the value for ta_tf_equipmet_data_new.KPSecondFatWeight
     *
     * @mbg.generated
     */
    public void setKpsecondfatweight(BigDecimal kpsecondfatweight) {
        this.kpsecondfatweight = kpsecondfatweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.XSAFatWeight
     *
     * @return the value of ta_tf_equipmet_data_new.XSAFatWeight
     *
     * @mbg.generated
     */
    public BigDecimal getXsafatweight() {
        return xsafatweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.XSAFatWeight
     *
     * @param xsafatweight the value for ta_tf_equipmet_data_new.XSAFatWeight
     *
     * @mbg.generated
     */
    public void setXsafatweight(BigDecimal xsafatweight) {
        this.xsafatweight = xsafatweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPFatGross
     *
     * @return the value of ta_tf_equipmet_data_new.KPFatGross
     *
     * @mbg.generated
     */
    public BigDecimal getKpfatgross() {
        return kpfatgross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPFatGross
     *
     * @param kpfatgross the value for ta_tf_equipmet_data_new.KPFatGross
     *
     * @mbg.generated
     */
    public void setKpfatgross(BigDecimal kpfatgross) {
        this.kpfatgross = kpfatgross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPSecondFatGross
     *
     * @return the value of ta_tf_equipmet_data_new.KPSecondFatGross
     *
     * @mbg.generated
     */
    public BigDecimal getKpsecondfatgross() {
        return kpsecondfatgross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPSecondFatGross
     *
     * @param kpsecondfatgross the value for ta_tf_equipmet_data_new.KPSecondFatGross
     *
     * @mbg.generated
     */
    public void setKpsecondfatgross(BigDecimal kpsecondfatgross) {
        this.kpsecondfatgross = kpsecondfatgross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.XSAFatGross
     *
     * @return the value of ta_tf_equipmet_data_new.XSAFatGross
     *
     * @mbg.generated
     */
    public BigDecimal getXsafatgross() {
        return xsafatgross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.XSAFatGross
     *
     * @param xsafatgross the value for ta_tf_equipmet_data_new.XSAFatGross
     *
     * @mbg.generated
     */
    public void setXsafatgross(BigDecimal xsafatgross) {
        this.xsafatgross = xsafatgross;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPFatLength
     *
     * @return the value of ta_tf_equipmet_data_new.KPFatLength
     *
     * @mbg.generated
     */
    public BigDecimal getKpfatlength() {
        return kpfatlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPFatLength
     *
     * @param kpfatlength the value for ta_tf_equipmet_data_new.KPFatLength
     *
     * @mbg.generated
     */
    public void setKpfatlength(BigDecimal kpfatlength) {
        this.kpfatlength = kpfatlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPSecondFatLength
     *
     * @return the value of ta_tf_equipmet_data_new.KPSecondFatLength
     *
     * @mbg.generated
     */
    public BigDecimal getKpsecondfatlength() {
        return kpsecondfatlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPSecondFatLength
     *
     * @param kpsecondfatlength the value for ta_tf_equipmet_data_new.KPSecondFatLength
     *
     * @mbg.generated
     */
    public void setKpsecondfatlength(BigDecimal kpsecondfatlength) {
        this.kpsecondfatlength = kpsecondfatlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.XSAFatLength
     *
     * @return the value of ta_tf_equipmet_data_new.XSAFatLength
     *
     * @mbg.generated
     */
    public BigDecimal getXsafatlength() {
        return xsafatlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.XSAFatLength
     *
     * @param xsafatlength the value for ta_tf_equipmet_data_new.XSAFatLength
     *
     * @mbg.generated
     */
    public void setXsafatlength(BigDecimal xsafatlength) {
        this.xsafatlength = xsafatlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPFatTotalLength
     *
     * @return the value of ta_tf_equipmet_data_new.KPFatTotalLength
     *
     * @mbg.generated
     */
    public BigDecimal getKpfattotallength() {
        return kpfattotallength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPFatTotalLength
     *
     * @param kpfattotallength the value for ta_tf_equipmet_data_new.KPFatTotalLength
     *
     * @mbg.generated
     */
    public void setKpfattotallength(BigDecimal kpfattotallength) {
        this.kpfattotallength = kpfattotallength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPSecondFatTotalLength
     *
     * @return the value of ta_tf_equipmet_data_new.KPSecondFatTotalLength
     *
     * @mbg.generated
     */
    public BigDecimal getKpsecondfattotallength() {
        return kpsecondfattotallength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPSecondFatTotalLength
     *
     * @param kpsecondfattotallength the value for ta_tf_equipmet_data_new.KPSecondFatTotalLength
     *
     * @mbg.generated
     */
    public void setKpsecondfattotallength(BigDecimal kpsecondfattotallength) {
        this.kpsecondfattotallength = kpsecondfattotallength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.XSAFatTotalLength
     *
     * @return the value of ta_tf_equipmet_data_new.XSAFatTotalLength
     *
     * @mbg.generated
     */
    public BigDecimal getXsafattotallength() {
        return xsafattotallength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.XSAFatTotalLength
     *
     * @param xsafattotallength the value for ta_tf_equipmet_data_new.XSAFatTotalLength
     *
     * @mbg.generated
     */
    public void setXsafattotallength(BigDecimal xsafattotallength) {
        this.xsafattotallength = xsafattotallength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.instantFlow
     *
     * @return the value of ta_tf_equipmet_data_new.instantFlow
     *
     * @mbg.generated
     */
    public BigDecimal getInstantflow() {
        return instantflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.instantFlow
     *
     * @param instantflow the value for ta_tf_equipmet_data_new.instantFlow
     *
     * @mbg.generated
     */
    public void setInstantflow(BigDecimal instantflow) {
        this.instantflow = instantflow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.pumpLaterPressure
     *
     * @return the value of ta_tf_equipmet_data_new.pumpLaterPressure
     *
     * @mbg.generated
     */
    public BigDecimal getPumplaterpressure() {
        return pumplaterpressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.pumpLaterPressure
     *
     * @param pumplaterpressure the value for ta_tf_equipmet_data_new.pumpLaterPressure
     *
     * @mbg.generated
     */
    public void setPumplaterpressure(BigDecimal pumplaterpressure) {
        this.pumplaterpressure = pumplaterpressure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPFatTanklevel
     *
     * @return the value of ta_tf_equipmet_data_new.KPFatTanklevel
     *
     * @mbg.generated
     */
    public BigDecimal getKpfattanklevel() {
        return kpfattanklevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPFatTanklevel
     *
     * @param kpfattanklevel the value for ta_tf_equipmet_data_new.KPFatTanklevel
     *
     * @mbg.generated
     */
    public void setKpfattanklevel(BigDecimal kpfattanklevel) {
        this.kpfattanklevel = kpfattanklevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPSecondFatTanklevel
     *
     * @return the value of ta_tf_equipmet_data_new.KPSecondFatTanklevel
     *
     * @mbg.generated
     */
    public BigDecimal getKpsecondfattanklevel() {
        return kpsecondfattanklevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPSecondFatTanklevel
     *
     * @param kpsecondfattanklevel the value for ta_tf_equipmet_data_new.KPSecondFatTanklevel
     *
     * @mbg.generated
     */
    public void setKpsecondfattanklevel(BigDecimal kpsecondfattanklevel) {
        this.kpsecondfattanklevel = kpsecondfattanklevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.XSAFatTanklevel
     *
     * @return the value of ta_tf_equipmet_data_new.XSAFatTanklevel
     *
     * @mbg.generated
     */
    public BigDecimal getXsafattanklevel() {
        return xsafattanklevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.XSAFatTanklevel
     *
     * @param xsafattanklevel the value for ta_tf_equipmet_data_new.XSAFatTanklevel
     *
     * @mbg.generated
     */
    public void setXsafattanklevel(BigDecimal xsafattanklevel) {
        this.xsafattanklevel = xsafattanklevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPFatWeightValue
     *
     * @return the value of ta_tf_equipmet_data_new.KPFatWeightValue
     *
     * @mbg.generated
     */
    public BigDecimal getKpfatweightvalue() {
        return kpfatweightvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPFatWeightValue
     *
     * @param kpfatweightvalue the value for ta_tf_equipmet_data_new.KPFatWeightValue
     *
     * @mbg.generated
     */
    public void setKpfatweightvalue(BigDecimal kpfatweightvalue) {
        this.kpfatweightvalue = kpfatweightvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPSecondFatWeightValue
     *
     * @return the value of ta_tf_equipmet_data_new.KPSecondFatWeightValue
     *
     * @mbg.generated
     */
    public BigDecimal getKpsecondfatweightvalue() {
        return kpsecondfatweightvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPSecondFatWeightValue
     *
     * @param kpsecondfatweightvalue the value for ta_tf_equipmet_data_new.KPSecondFatWeightValue
     *
     * @mbg.generated
     */
    public void setKpsecondfatweightvalue(BigDecimal kpsecondfatweightvalue) {
        this.kpsecondfatweightvalue = kpsecondfatweightvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.XSAFatWeightValue
     *
     * @return the value of ta_tf_equipmet_data_new.XSAFatWeightValue
     *
     * @mbg.generated
     */
    public BigDecimal getXsafatweightvalue() {
        return xsafatweightvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.XSAFatWeightValue
     *
     * @param xsafatweightvalue the value for ta_tf_equipmet_data_new.XSAFatWeightValue
     *
     * @mbg.generated
     */
    public void setXsafatweightvalue(BigDecimal xsafatweightvalue) {
        this.xsafatweightvalue = xsafatweightvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPFatCompensationValue
     *
     * @return the value of ta_tf_equipmet_data_new.KPFatCompensationValue
     *
     * @mbg.generated
     */
    public BigDecimal getKpfatcompensationvalue() {
        return kpfatcompensationvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPFatCompensationValue
     *
     * @param kpfatcompensationvalue the value for ta_tf_equipmet_data_new.KPFatCompensationValue
     *
     * @mbg.generated
     */
    public void setKpfatcompensationvalue(BigDecimal kpfatcompensationvalue) {
        this.kpfatcompensationvalue = kpfatcompensationvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPSecondFatCompensationValue
     *
     * @return the value of ta_tf_equipmet_data_new.KPSecondFatCompensationValue
     *
     * @mbg.generated
     */
    public BigDecimal getKpsecondfatcompensationvalue() {
        return kpsecondfatcompensationvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPSecondFatCompensationValue
     *
     * @param kpsecondfatcompensationvalue the value for ta_tf_equipmet_data_new.KPSecondFatCompensationValue
     *
     * @mbg.generated
     */
    public void setKpsecondfatcompensationvalue(BigDecimal kpsecondfatcompensationvalue) {
        this.kpsecondfatcompensationvalue = kpsecondfatcompensationvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.XSAFatCompensationValue
     *
     * @return the value of ta_tf_equipmet_data_new.XSAFatCompensationValue
     *
     * @mbg.generated
     */
    public BigDecimal getXsafatcompensationvalue() {
        return xsafatcompensationvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.XSAFatCompensationValue
     *
     * @param xsafatcompensationvalue the value for ta_tf_equipmet_data_new.XSAFatCompensationValue
     *
     * @mbg.generated
     */
    public void setXsafatcompensationvalue(BigDecimal xsafatcompensationvalue) {
        this.xsafatcompensationvalue = xsafatcompensationvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.pumpLaterPressureLowValue
     *
     * @return the value of ta_tf_equipmet_data_new.pumpLaterPressureLowValue
     *
     * @mbg.generated
     */
    public BigDecimal getPumplaterpressurelowvalue() {
        return pumplaterpressurelowvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.pumpLaterPressureLowValue
     *
     * @param pumplaterpressurelowvalue the value for ta_tf_equipmet_data_new.pumpLaterPressureLowValue
     *
     * @mbg.generated
     */
    public void setPumplaterpressurelowvalue(BigDecimal pumplaterpressurelowvalue) {
        this.pumplaterpressurelowvalue = pumplaterpressurelowvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.FlowLowValue
     *
     * @return the value of ta_tf_equipmet_data_new.FlowLowValue
     *
     * @mbg.generated
     */
    public BigDecimal getFlowlowvalue() {
        return flowlowvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.FlowLowValue
     *
     * @param flowlowvalue the value for ta_tf_equipmet_data_new.FlowLowValue
     *
     * @mbg.generated
     */
    public void setFlowlowvalue(BigDecimal flowlowvalue) {
        this.flowlowvalue = flowlowvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.pumpFrequencyValue
     *
     * @return the value of ta_tf_equipmet_data_new.pumpFrequencyValue
     *
     * @mbg.generated
     */
    public BigDecimal getPumpfrequencyvalue() {
        return pumpfrequencyvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.pumpFrequencyValue
     *
     * @param pumpfrequencyvalue the value for ta_tf_equipmet_data_new.pumpFrequencyValue
     *
     * @mbg.generated
     */
    public void setPumpfrequencyvalue(BigDecimal pumpfrequencyvalue) {
        this.pumpfrequencyvalue = pumpfrequencyvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPPushFatNumber
     *
     * @return the value of ta_tf_equipmet_data_new.KPPushFatNumber
     *
     * @mbg.generated
     */
    public BigDecimal getKppushfatnumber() {
        return kppushfatnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPPushFatNumber
     *
     * @param kppushfatnumber the value for ta_tf_equipmet_data_new.KPPushFatNumber
     *
     * @mbg.generated
     */
    public void setKppushfatnumber(BigDecimal kppushfatnumber) {
        this.kppushfatnumber = kppushfatnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.KPSecondPushFatNumber
     *
     * @return the value of ta_tf_equipmet_data_new.KPSecondPushFatNumber
     *
     * @mbg.generated
     */
    public BigDecimal getKpsecondpushfatnumber() {
        return kpsecondpushfatnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.KPSecondPushFatNumber
     *
     * @param kpsecondpushfatnumber the value for ta_tf_equipmet_data_new.KPSecondPushFatNumber
     *
     * @mbg.generated
     */
    public void setKpsecondpushfatnumber(BigDecimal kpsecondpushfatnumber) {
        this.kpsecondpushfatnumber = kpsecondpushfatnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ta_tf_equipmet_data_new.XSAPushFatNumber
     *
     * @return the value of ta_tf_equipmet_data_new.XSAPushFatNumber
     *
     * @mbg.generated
     */
    public BigDecimal getXsapushfatnumber() {
        return xsapushfatnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ta_tf_equipmet_data_new.XSAPushFatNumber
     *
     * @param xsapushfatnumber the value for ta_tf_equipmet_data_new.XSAPushFatNumber
     *
     * @mbg.generated
     */
    public void setXsapushfatnumber(BigDecimal xsapushfatnumber) {
        this.xsapushfatnumber = xsapushfatnumber;
    }
}